service: typeup-app-api

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2

  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"


# resources:
#   dynamoDB table
#   S3 bucket
#   Cognito user pool (current pool arn: arn:aws:cognito-idp:us-west-2:402153944964:userpool/us-west-2_7TooDx4yJ)
#   Cognito App client (current id: 2sdk53svubdtll8gigcscjb0an)

# DynamoDB tables:
# - users
#   - field: id, email, name
#  - primary index on id, sort by name
#  - secondary index on cognitoId, sort by name
#  - Main query: get all users sorted by name.

# FOR COGNITO: username should be email, email should be email, add name to a 'name' attribute field

# - statuses
#  - primary index on id, sorty by createdAt.
#  - secondary index on... do we need a secondary index
#  - Main query: get a user's most recent status, so query by userId, sort by createdAt, get most recent. Then in code, check if it's from today
#

functions:

  list_users:
    handler: list_users.main
    events:
      - http:
          path: users
          method: get
          # cors: true
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer: aws_iam

  create_user:
    handler: create_user.main
    events:
      - http:
          path: users
          method: post
          # cors: true
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer: aws_iam

  create:
    # Defines an HTTP API endpoint that calls the main function in create.js
    # - path: url path is /statuses
    # - method: POST request
    # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
    #     domain api call
    # - authorizer: authenticate using the AWS IAM role
    handler: create.main
    events:
      - http:
          path: statuses
          method: post
          # cors: true
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer: aws_iam

  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /statuses/{id}
    # - method: GET request
    handler: get.main
    events:
      - http:
          path: statuses/{id}
          method: get
          cors: true
          # cors:
          #   origin: '*'
          #   headers:
          #     - Content-Type
          #     - X-Amz-Date
          #     - Authorization
          #     - X-Api-Key
          #     - X-Amz-Security-Token
          #     - X-Amz-User-Agent
          #   allowCredentials: false
          authorizer: aws_iam

  list:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /statuses
    # - method: GET request
    handler: list.main
    events:
      - http:
          path: statuses
          method: get
          # cors: true
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer: aws_iam

  update:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /statuses/{id}
    # - method: PUT request
    handler: update.main
    events:
      - http:
          path: statuses/{id}
          method: put
          # cors: true
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer: aws_iam

  delete:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is /statuses/{id}
    # - method: DELETE request
    handler: delete.main
    events:
      - http:
          path: statuses/{id}
          method: delete
          # cors: true
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer: aws_iam
